- name: Clean Directory
  file:
    path: "{{ docker_folder }}"
    state: absent

- name: Create Resources Folder
  file:
    path: "{{ docker_folder }}"
    state: directory

- name: Clone
  git:
    repo: "http://{{ username }}:{{ password }}@{{ adopserver }}/gitlab/{{ adopuser }}/tomcat.git"
    dest: "{{ docker_folder }}"

- name: Download war file
  get_url:
    url: http://{{ adopserver }}/nexus/content/repositories/snapshots/{{ groupId }}/CurrencyConverter/1/CurrencyConverter-1.war
    dest: "{{ docker_folder }}/Resources/CurrencyConverter-1.war"
    mode: 0644
    url_password: "{{ password }}"
    url_username: "{{ username }}"

- name: Check
  shell: "pwd && ls -lart && whoami"
  register: output
  
- name: Display
  debug: var=output
